"""empty message

Revision ID: 1c28c0ff3ee7
Revises: 
Create Date: 2022-10-01 14:30:08.780137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c28c0ff3ee7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('activity_description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('activity_id')
    )
    op.create_table('breeds',
    sa.Column('breed_id', sa.Integer(), nullable=False),
    sa.Column('breed_name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('breed_id')
    )
    op.create_table('matches',
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('dog_id_one', sa.Integer(), nullable=True),
    sa.Column('dog_id_two', sa.Integer(), nullable=True),
    sa.Column('creation_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('match_id')
    )
    op.create_table('sizes',
    sa.Column('size_id', sa.Integer(), nullable=False),
    sa.Column('size', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('size_id')
    )
    op.create_table('temperaments',
    sa.Column('temperament_id', sa.Integer(), nullable=False),
    sa.Column('temperament_type', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('temperament_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('gender', sa.Text(), nullable=True),
    sa.Column('user_pic', sa.Text(), nullable=True),
    sa.Column('user_bio', sa.Text(), nullable=True),
    sa.Column('role', sa.Text(), nullable=True),
    sa.Column('max_distance', sa.Integer(), nullable=True),
    sa.Column('zipcode', sa.Text(), nullable=True),
    sa.Column('creation_time', sa.DateTime(), nullable=True),
    sa.Column('last_update', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('dogs',
    sa.Column('dog_id', sa.Integer(), nullable=False),
    sa.Column('dog_name', sa.Text(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('breed_id', sa.Integer(), nullable=False),
    sa.Column('size_id', sa.Integer(), nullable=False),
    sa.Column('temperament_id', sa.Integer(), nullable=False),
    sa.Column('age', sa.Text(), nullable=False),
    sa.Column('sex', sa.Text(), nullable=False),
    sa.Column('is_vaccinated', sa.Boolean(), nullable=False),
    sa.Column('is_fixed', sa.Boolean(), nullable=False),
    sa.Column('dog_bio', sa.Text(), nullable=True),
    sa.Column('dog_pic', sa.Text(), nullable=True),
    sa.Column('creation_time', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['breed_id'], ['breeds.breed_id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['size_id'], ['sizes.size_id'], ),
    sa.ForeignKeyConstraint(['temperament_id'], ['temperaments.temperament_id'], ),
    sa.PrimaryKeyConstraint('dog_id'),
    sa.UniqueConstraint('dog_id', 'owner_id', name='unique_dog_const')
    )
    op.create_table('dog_activities',
    sa.Column('dog_activity_id', sa.Integer(), nullable=False),
    sa.Column('dog_id', sa.Integer(), nullable=True),
    sa.Column('activity_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.activity_id'], ),
    sa.ForeignKeyConstraint(['dog_id'], ['dogs.dog_id'], ),
    sa.PrimaryKeyConstraint('dog_activity_id')
    )
    op.create_table('swipes',
    sa.Column('swipe_id', sa.Integer(), nullable=False),
    sa.Column('dog_id', sa.Integer(), nullable=True),
    sa.Column('swiped_dog_id', sa.Integer(), nullable=True),
    sa.Column('is_interested', sa.Boolean(), nullable=True),
    sa.Column('creation_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dog_id'], ['dogs.dog_id'], ),
    sa.ForeignKeyConstraint(['swiped_dog_id'], ['dogs.dog_id'], ),
    sa.PrimaryKeyConstraint('swipe_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('swipes')
    op.drop_table('dog_activities')
    op.drop_table('dogs')
    op.drop_table('users')
    op.drop_table('temperaments')
    op.drop_table('sizes')
    op.drop_table('matches')
    op.drop_table('breeds')
    op.drop_table('activities')
    # ### end Alembic commands ###
